//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fisk.EnterpriseManageDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfo
    {
        public int Id { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAbbreviation { get; set; }
        public string TaxNumber { get; set; }
        public string CompanyAddress { get; set; }
        public Nullable<int> Telephone { get; set; }
        public string Contacts { get; set; }
        public string ContactTitle { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<int> Validty { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserId { get; set; }
        public string CreateName { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyName { get; set; }
    }
}
