//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fisk.EnterpriseManageDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInfo
    {
        public int Id { get; set; }
        public string ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string ProjectTypeId { get; set; }
        public string ProjectType { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string PMid { get; set; }
        public string PMname { get; set; }
        public Nullable<int> PMdepartmentID { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<System.DateTime> SigningTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> ContractDays { get; set; }
        public Nullable<System.DateTime> EstimateEndTime { get; set; }
        public Nullable<int> ProjectStatusId { get; set; }
        public string ProjectStatus { get; set; }
        public Nullable<int> EstimateManDay { get; set; }
        public Nullable<System.DateTime> ActualEndTime { get; set; }
        public Nullable<decimal> ActualManDay { get; set; }
        public string ProjectProgress { get; set; }
        public string ProjectHealth { get; set; }
        public Nullable<int> Validty { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserId { get; set; }
        public string CreateName { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyName { get; set; }
    }
}
