//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fisk.EnterpriseManageDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyDetail
    {
        public int Id { get; set; }
        public string ProjectId { get; set; }
        public string ProjectProgress { get; set; }
        public string ProjectStatus { get; set; }
        public string ActualDays { get; set; }
        public string TimeProgress { get; set; }
        public string ImplementationProgress { get; set; }
        public string PersonnelUse { get; set; }
        public string WeeklyContent { get; set; }
        public string Differences { get; set; }
        public string NextWeekPlans { get; set; }
        public string Position { get; set; }
        public string NaturalWeek { get; set; }
        public string ProjectWeek { get; set; }
        public Nullable<int> Validty { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserId { get; set; }
        public string CreateName { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyName { get; set; }
        public string ContractDays { get; set; }
    }
}
